// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, model, name, hardware_id, firmware_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, model, name, hardware_id, firmware_version, created_at, last_seen_at, last_puff_at, vaping_since, latest_status
`

type CreateDeviceParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Model           string      `json:"model"`
	Name            string      `json:"name"`
	HardwareID      string      `json:"hardware_id"`
	FirmwareVersion pgtype.Text `json:"firmware_version"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Model,
		arg.Name,
		arg.HardwareID,
		arg.FirmwareVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Name,
		&i.HardwareID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastPuffAt,
		&i.VapingSince,
		&i.LatestStatus,
	)
	return i, err
}

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (id, device_id, name, token_hash)
VALUES ($1, $2, $3, $4) RETURNING id, device_id, name, token_hash, created_at, last_used_at, revoked_at
`

type CreateDeviceTokenParams struct {
	ID        pgtype.UUID `json:"id"`
	DeviceID  pgtype.UUID `json:"device_id"`
	Name      string      `json:"name"`
	TokenHash []byte      `json:"token_hash"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.ID,
		arg.DeviceID,
		arg.Name,
		arg.TokenHash,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, model, name, hardware_id, firmware_version, created_at, last_seen_at, last_puff_at, vaping_since, latest_status FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Name,
		&i.HardwareID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastPuffAt,
		&i.VapingSince,
		&i.LatestStatus,
	)
	return i, err
}

const getDeviceByUserHardware = `-- name: GetDeviceByUserHardware :one
SELECT id, user_id, model, name, hardware_id, firmware_version, created_at, last_seen_at, last_puff_at, vaping_since, latest_status FROM devices WHERE user_id = $1 AND hardware_id = $2
`

type GetDeviceByUserHardwareParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	HardwareID string      `json:"hardware_id"`
}

func (q *Queries) GetDeviceByUserHardware(ctx context.Context, arg GetDeviceByUserHardwareParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByUserHardware, arg.UserID, arg.HardwareID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Name,
		&i.HardwareID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastPuffAt,
		&i.VapingSince,
		&i.LatestStatus,
	)
	return i, err
}

const getDeviceTokenByHash = `-- name: GetDeviceTokenByHash :one
SELECT
    dt.id, dt.device_id, dt.name, dt.token_hash, dt.created_at, dt.last_used_at, dt.revoked_at,
    d.user_id AS owner_user_id
FROM device_tokens dt
JOIN devices d ON d.id = dt.device_id
WHERE dt.token_hash = $1 AND dt.revoked_at IS NULL
`

type GetDeviceTokenByHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
}

func (q *Queries) GetDeviceTokenByHash(ctx context.Context, tokenHash []byte) (GetDeviceTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByHash, tokenHash)
	var i GetDeviceTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.OwnerUserID,
	)
	return i, err
}

const listDeviceTokens = `-- name: ListDeviceTokens :many
SELECT id, device_id, name, token_hash, created_at, last_used_at, revoked_at FROM device_tokens WHERE device_id = $1 ORDER BY created_at
`

func (q *Queries) ListDeviceTokens(ctx context.Context, deviceID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokens, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, model, name, hardware_id, firmware_version, created_at, last_seen_at, last_puff_at, vaping_since, latest_status FROM devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Model,
			&i.Name,
			&i.HardwareID,
			&i.FirmwareVersion,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.LastPuffAt,
			&i.VapingSince,
			&i.LatestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllDeviceTokens = `-- name: RevokeAllDeviceTokens :exec
UPDATE device_tokens SET revoked_at = now() WHERE device_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllDeviceTokens(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllDeviceTokens, deviceID)
	return err
}

const revokeDeviceToken = `-- name: RevokeDeviceToken :exec
UPDATE device_tokens SET revoked_at = now()
WHERE id = $1 AND device_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceTokenParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeDeviceToken(ctx context.Context, arg RevokeDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceToken, arg.ID, arg.DeviceID)
	return err
}

const touchDeviceTokenLastUsed = `-- name: TouchDeviceTokenLastUsed :exec
UPDATE device_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchDeviceTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchDeviceTokenLastUsed, id)
	return err
}

const updateDeviceLiveState = `-- name: UpdateDeviceLiveState :exec
UPDATE devices SET
    last_seen_at = COALESCE($2, last_seen_at),
    last_puff_at = COALESCE($3, last_puff_at),
    vaping_since = $4,
    latest_status = COALESCE($5, latest_status),
    firmware_version = COALESCE($6, firmware_version)
WHERE id = $1
`

type UpdateDeviceLiveStateParams struct {
	ID              pgtype.UUID        `json:"id"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	LastPuffAt      pgtype.Timestamptz `json:"last_puff_at"`
	VapingSince     pgtype.Timestamptz `json:"vaping_since"`
	LatestStatus    []byte             `json:"latest_status"`
	FirmwareVersion pgtype.Text        `json:"firmware_version"`
}

func (q *Queries) UpdateDeviceLiveState(ctx context.Context, arg UpdateDeviceLiveStateParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLiveState,
		arg.ID,
		arg.LastSeenAt,
		arg.LastPuffAt,
		arg.VapingSince,
		arg.LatestStatus,
		arg.FirmwareVersion,
	)
	return err
}

const updateDeviceName = `-- name: UpdateDeviceName :one
UPDATE devices SET name = $2 WHERE id = $1 AND user_id = $3 RETURNING id, user_id, model, name, hardware_id, firmware_version, created_at, last_seen_at, last_puff_at, vaping_since, latest_status
`

type UpdateDeviceNameParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceName, arg.ID, arg.Name, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Name,
		&i.HardwareID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastPuffAt,
		&i.VapingSince,
		&i.LatestStatus,
	)
	return i, err
}
