// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Role    string      `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*)::int FROM group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, owner_id, invite_code) VALUES ($1, $2, $3, $4) RETURNING id, name, owner_id, invite_code, created_at
`

type CreateGroupParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	InviteCode string      `json:"invite_code"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.InviteCode,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const demoteOwnerToAdmin = `-- name: DemoteOwnerToAdmin :exec
UPDATE group_members SET role = 'admin' WHERE group_id = $1 AND user_id = $2 AND role = 'owner'
`

type DemoteOwnerToAdminParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DemoteOwnerToAdmin(ctx context.Context, arg DemoteOwnerToAdminParams) error {
	_, err := q.db.Exec(ctx, demoteOwnerToAdmin, arg.GroupID, arg.UserID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, owner_id, invite_code, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, owner_id, invite_code, created_at FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT gm.group_id, gm.user_id, gm.role, gm.joined_at, u.display_name
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND gm.user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetGroupMemberRow struct {
	GroupID     pgtype.UUID        `json:"group_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GetGroupMemberRow, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GetGroupMemberRow
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.DisplayName,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.group_id, gm.user_id, gm.role, gm.joined_at, u.display_name
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at
`

type ListGroupMembersRow struct {
	GroupID     pgtype.UUID        `json:"group_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.created_at, gm.role,
       (SELECT count(*)::int FROM group_members WHERE group_id = g.id) AS member_count
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type ListUserGroupsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        string             `json:"role"`
	MemberCount int32              `json:"member_count"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID pgtype.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteMemberToOwner = `-- name: PromoteMemberToOwner :exec
UPDATE group_members SET role = 'owner' WHERE group_id = $1 AND user_id = $2
`

type PromoteMemberToOwnerParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) PromoteMemberToOwner(ctx context.Context, arg PromoteMemberToOwnerParams) error {
	_, err := q.db.Exec(ctx, promoteMemberToOwner, arg.GroupID, arg.UserID)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const setGroupOwner = `-- name: SetGroupOwner :exec
UPDATE groups SET owner_id = $2 WHERE id = $1
`

type SetGroupOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) SetGroupOwner(ctx context.Context, arg SetGroupOwnerParams) error {
	_, err := q.db.Exec(ctx, setGroupOwner, arg.ID, arg.OwnerID)
	return err
}

const updateGroupInviteCode = `-- name: UpdateGroupInviteCode :one
UPDATE groups SET invite_code = $2 WHERE id = $1 RETURNING id, name, owner_id, invite_code, created_at
`

type UpdateGroupInviteCodeParams struct {
	ID         pgtype.UUID `json:"id"`
	InviteCode string      `json:"invite_code"`
}

func (q *Queries) UpdateGroupInviteCode(ctx context.Context, arg UpdateGroupInviteCodeParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupInviteCode, arg.ID, arg.InviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :exec
UPDATE group_members SET role = $3 WHERE group_id = $1 AND user_id = $2
`

type UpdateGroupMemberRoleParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Role    string      `json:"role"`
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateGroupMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups SET name = $2 WHERE id = $1 RETURNING id, name, owner_id, invite_code, created_at
`

type UpdateGroupNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}
