// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Model           string             `json:"model"`
	Name            string             `json:"name"`
	HardwareID      string             `json:"hardware_id"`
	FirmwareVersion pgtype.Text        `json:"firmware_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	LastPuffAt      pgtype.Timestamptz `json:"last_puff_at"`
	VapingSince     pgtype.Timestamptz `json:"vaping_since"`
	LatestStatus    []byte             `json:"latest_status"`
}

type DeviceStatusSnapshot struct {
	ID            pgtype.UUID        `json:"id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientEventID pgtype.UUID        `json:"client_event_id"`
	RecordedAt    pgtype.Timestamptz `json:"recorded_at"`
	Status        []byte             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DeviceToken struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	Name       string             `json:"name"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Group struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	InviteCode string             `json:"invite_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type GroupPrivacyOverride struct {
	GroupID           pgtype.UUID `json:"group_id"`
	UserID            pgtype.UUID `json:"user_id"`
	ShareLiveStatus   pgtype.Bool `json:"share_live_status"`
	ShareUsageSummary pgtype.Bool `json:"share_usage_summary"`
	ShareUsageDetail  pgtype.Bool `json:"share_usage_detail"`
	ShareDeviceStats  pgtype.Bool `json:"share_device_stats"`
	ShowInLeaderboard pgtype.Bool `json:"show_in_leaderboard"`
}

type PrivacyDefault struct {
	UserID            pgtype.UUID `json:"user_id"`
	ShareLiveStatus   bool        `json:"share_live_status"`
	ShareUsageSummary bool        `json:"share_usage_summary"`
	ShareUsageDetail  bool        `json:"share_usage_detail"`
	ShareDeviceStats  bool        `json:"share_device_stats"`
	ShowInLeaderboard bool        `json:"show_in_leaderboard"`
}

type Puff struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	ClientEventID pgtype.UUID        `json:"client_event_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	DurationMs    int32              `json:"duration_ms"`
	Source        string             `json:"source"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	Raw           []byte             `json:"raw"`
}

type RefreshToken struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	TokenHash      []byte             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RotatedAt      pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	GraceTokenHash []byte             `json:"grace_token_hash"`
	GraceExpiresAt pgtype.Timestamptz `json:"grace_expires_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	EmailLower   pgtype.Text        `json:"email_lower"`
	DisplayName  string             `json:"display_name"`
	Timezone     string             `json:"timezone"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
