// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canViewCapability = `-- name: CanViewCapability :one
SELECT EXISTS (
    SELECT 1
    FROM group_members viewer
    JOIN group_members target ON target.group_id = viewer.group_id AND target.user_id = $1
    JOIN privacy_defaults pd ON pd.user_id = target.user_id
    LEFT JOIN group_privacy_overrides gpo ON gpo.group_id = viewer.group_id AND gpo.user_id = target.user_id
    WHERE viewer.user_id = $2
      AND ($3::uuid IS NULL OR viewer.group_id = $3)
      AND CASE $4::text
        WHEN 'share_live_status' THEN COALESCE(gpo.share_live_status, pd.share_live_status)
        WHEN 'share_usage_summary' THEN COALESCE(gpo.share_usage_summary, pd.share_usage_summary)
        WHEN 'share_usage_detail' THEN COALESCE(gpo.share_usage_detail, pd.share_usage_detail)
        WHEN 'share_device_stats' THEN COALESCE(gpo.share_device_stats, pd.share_device_stats)
        WHEN 'show_in_leaderboard' THEN COALESCE(gpo.show_in_leaderboard, pd.show_in_leaderboard)
      END = true
) AS allowed
`

type CanViewCapabilityParams struct {
	TargetUserID pgtype.UUID `json:"target_user_id"`
	ViewerUserID pgtype.UUID `json:"viewer_user_id"`
	GroupID      pgtype.UUID `json:"group_id"`
	Capability   string      `json:"capability"`
}

func (q *Queries) CanViewCapability(ctx context.Context, arg CanViewCapabilityParams) (bool, error) {
	row := q.db.QueryRow(ctx, canViewCapability,
		arg.TargetUserID,
		arg.ViewerUserID,
		arg.GroupID,
		arg.Capability,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const getGroupPrivacyOverride = `-- name: GetGroupPrivacyOverride :one
SELECT group_id, user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard FROM group_privacy_overrides WHERE group_id = $1 AND user_id = $2
`

type GetGroupPrivacyOverrideParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupPrivacyOverride(ctx context.Context, arg GetGroupPrivacyOverrideParams) (GroupPrivacyOverride, error) {
	row := q.db.QueryRow(ctx, getGroupPrivacyOverride, arg.GroupID, arg.UserID)
	var i GroupPrivacyOverride
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.ShareLiveStatus,
		&i.ShareUsageSummary,
		&i.ShareUsageDetail,
		&i.ShareDeviceStats,
		&i.ShowInLeaderboard,
	)
	return i, err
}

const getPrivacyDefaults = `-- name: GetPrivacyDefaults :one
SELECT user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard FROM privacy_defaults WHERE user_id = $1
`

func (q *Queries) GetPrivacyDefaults(ctx context.Context, userID pgtype.UUID) (PrivacyDefault, error) {
	row := q.db.QueryRow(ctx, getPrivacyDefaults, userID)
	var i PrivacyDefault
	err := row.Scan(
		&i.UserID,
		&i.ShareLiveStatus,
		&i.ShareUsageSummary,
		&i.ShareUsageDetail,
		&i.ShareDeviceStats,
		&i.ShowInLeaderboard,
	)
	return i, err
}

const upsertGroupPrivacyOverride = `-- name: UpsertGroupPrivacyOverride :one
INSERT INTO group_privacy_overrides (group_id, user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (group_id, user_id) DO UPDATE SET
    share_live_status = EXCLUDED.share_live_status,
    share_usage_summary = EXCLUDED.share_usage_summary,
    share_usage_detail = EXCLUDED.share_usage_detail,
    share_device_stats = EXCLUDED.share_device_stats,
    show_in_leaderboard = EXCLUDED.show_in_leaderboard
RETURNING group_id, user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard
`

type UpsertGroupPrivacyOverrideParams struct {
	GroupID           pgtype.UUID `json:"group_id"`
	UserID            pgtype.UUID `json:"user_id"`
	ShareLiveStatus   pgtype.Bool `json:"share_live_status"`
	ShareUsageSummary pgtype.Bool `json:"share_usage_summary"`
	ShareUsageDetail  pgtype.Bool `json:"share_usage_detail"`
	ShareDeviceStats  pgtype.Bool `json:"share_device_stats"`
	ShowInLeaderboard pgtype.Bool `json:"show_in_leaderboard"`
}

func (q *Queries) UpsertGroupPrivacyOverride(ctx context.Context, arg UpsertGroupPrivacyOverrideParams) (GroupPrivacyOverride, error) {
	row := q.db.QueryRow(ctx, upsertGroupPrivacyOverride,
		arg.GroupID,
		arg.UserID,
		arg.ShareLiveStatus,
		arg.ShareUsageSummary,
		arg.ShareUsageDetail,
		arg.ShareDeviceStats,
		arg.ShowInLeaderboard,
	)
	var i GroupPrivacyOverride
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.ShareLiveStatus,
		&i.ShareUsageSummary,
		&i.ShareUsageDetail,
		&i.ShareDeviceStats,
		&i.ShowInLeaderboard,
	)
	return i, err
}

const upsertPrivacyDefaults = `-- name: UpsertPrivacyDefaults :one
INSERT INTO privacy_defaults (user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    share_live_status = EXCLUDED.share_live_status,
    share_usage_summary = EXCLUDED.share_usage_summary,
    share_usage_detail = EXCLUDED.share_usage_detail,
    share_device_stats = EXCLUDED.share_device_stats,
    show_in_leaderboard = EXCLUDED.show_in_leaderboard
RETURNING user_id, share_live_status, share_usage_summary, share_usage_detail, share_device_stats, show_in_leaderboard
`

type UpsertPrivacyDefaultsParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	ShareLiveStatus   bool        `json:"share_live_status"`
	ShareUsageSummary bool        `json:"share_usage_summary"`
	ShareUsageDetail  bool        `json:"share_usage_detail"`
	ShareDeviceStats  bool        `json:"share_device_stats"`
	ShowInLeaderboard bool        `json:"show_in_leaderboard"`
}

func (q *Queries) UpsertPrivacyDefaults(ctx context.Context, arg UpsertPrivacyDefaultsParams) (PrivacyDefault, error) {
	row := q.db.QueryRow(ctx, upsertPrivacyDefaults,
		arg.UserID,
		arg.ShareLiveStatus,
		arg.ShareUsageSummary,
		arg.ShareUsageDetail,
		arg.ShareDeviceStats,
		arg.ShowInLeaderboard,
	)
	var i PrivacyDefault
	err := row.Scan(
		&i.UserID,
		&i.ShareLiveStatus,
		&i.ShareUsageSummary,
		&i.ShareUsageDetail,
		&i.ShareDeviceStats,
		&i.ShowInLeaderboard,
	)
	return i, err
}
