// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: puffs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPuff = `-- name: InsertPuff :one
INSERT INTO puffs (id, user_id, device_id, client_event_id, started_at, duration_ms, source, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (device_id, client_event_id) DO NOTHING
RETURNING id, user_id, device_id, client_event_id, started_at, duration_ms, source, received_at, raw
`

type InsertPuffParams struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	ClientEventID pgtype.UUID        `json:"client_event_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	DurationMs    int32              `json:"duration_ms"`
	Source        string             `json:"source"`
	Raw           []byte             `json:"raw"`
}

func (q *Queries) InsertPuff(ctx context.Context, arg InsertPuffParams) (Puff, error) {
	row := q.db.QueryRow(ctx, insertPuff,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.ClientEventID,
		arg.StartedAt,
		arg.DurationMs,
		arg.Source,
		arg.Raw,
	)
	var i Puff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ClientEventID,
		&i.StartedAt,
		&i.DurationMs,
		&i.Source,
		&i.ReceivedAt,
		&i.Raw,
	)
	return i, err
}

const insertStatusSnapshot = `-- name: InsertStatusSnapshot :one
INSERT INTO device_status_snapshots (id, device_id, user_id, client_event_id, recorded_at, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (device_id, client_event_id) DO NOTHING
RETURNING id, device_id, user_id, client_event_id, recorded_at, status, created_at
`

type InsertStatusSnapshotParams struct {
	ID            pgtype.UUID        `json:"id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientEventID pgtype.UUID        `json:"client_event_id"`
	RecordedAt    pgtype.Timestamptz `json:"recorded_at"`
	Status        []byte             `json:"status"`
}

func (q *Queries) InsertStatusSnapshot(ctx context.Context, arg InsertStatusSnapshotParams) (DeviceStatusSnapshot, error) {
	row := q.db.QueryRow(ctx, insertStatusSnapshot,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.ClientEventID,
		arg.RecordedAt,
		arg.Status,
	)
	var i DeviceStatusSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.ClientEventID,
		&i.RecordedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPuffs = `-- name: ListPuffs :many
SELECT id, user_id, device_id, client_event_id, started_at, duration_ms, source, received_at, raw FROM puffs
WHERE user_id = $1
  AND started_at >= $2
  AND started_at < $3
  AND ($5::uuid IS NULL OR device_id = $5)
  AND ($6::text IS NULL OR source = $6)
  AND ($7::int IS NULL OR duration_ms >= $7)
  AND ($8::int IS NULL OR duration_ms <= $8)
  AND (
    $9::timestamptz IS NULL
    OR (started_at, id) < ($9, $10::uuid)
  )
ORDER BY started_at DESC, id DESC
LIMIT $4
`

type ListPuffsParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	StartedAt_2     pgtype.Timestamptz `json:"started_at_2"`
	Limit           int32              `json:"limit"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	Source          pgtype.Text        `json:"source"`
	MinDurationMs   pgtype.Int4        `json:"min_duration_ms"`
	MaxDurationMs   pgtype.Int4        `json:"max_duration_ms"`
	CursorStartedAt pgtype.Timestamptz `json:"cursor_started_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

func (q *Queries) ListPuffs(ctx context.Context, arg ListPuffsParams) ([]Puff, error) {
	rows, err := q.db.Query(ctx, listPuffs,
		arg.UserID,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.Limit,
		arg.DeviceID,
		arg.Source,
		arg.MinDurationMs,
		arg.MaxDurationMs,
		arg.CursorStartedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Puff
	for rows.Next() {
		var i Puff
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.ClientEventID,
			&i.StartedAt,
			&i.DurationMs,
			&i.Source,
			&i.ReceivedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPuffsAsc = `-- name: ListPuffsAsc :many
SELECT id, user_id, device_id, client_event_id, started_at, duration_ms, source, received_at, raw FROM puffs
WHERE user_id = $1
  AND started_at >= $2
  AND started_at < $3
  AND ($5::uuid IS NULL OR device_id = $5)
  AND ($6::text IS NULL OR source = $6)
  AND (
    $7::timestamptz IS NULL
    OR (started_at, id) > ($7, $8::uuid)
  )
ORDER BY started_at ASC, id ASC
LIMIT $4
`

type ListPuffsAscParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	StartedAt_2     pgtype.Timestamptz `json:"started_at_2"`
	Limit           int32              `json:"limit"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	Source          pgtype.Text        `json:"source"`
	CursorStartedAt pgtype.Timestamptz `json:"cursor_started_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

func (q *Queries) ListPuffsAsc(ctx context.Context, arg ListPuffsAscParams) ([]Puff, error) {
	rows, err := q.db.Query(ctx, listPuffsAsc,
		arg.UserID,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.Limit,
		arg.DeviceID,
		arg.Source,
		arg.CursorStartedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Puff
	for rows.Next() {
		var i Puff
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.ClientEventID,
			&i.StartedAt,
			&i.DurationMs,
			&i.Source,
			&i.ReceivedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
