// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, session_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id, session_id, token_hash, expires_at, created_at, rotated_at, revoked_at, grace_token_hash, grace_expires_at
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.GraceTokenHash,
		&i.GraceExpiresAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id) VALUES ($1, $2) RETURNING id, user_id, created_at, revoked_at
`

type CreateSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByGraceHash = `-- name: GetRefreshTokenByGraceHash :one
SELECT id, session_id, token_hash, expires_at, created_at, rotated_at, revoked_at, grace_token_hash, grace_expires_at FROM refresh_tokens
WHERE grace_token_hash = $1 AND grace_expires_at > now() AND revoked_at IS NULL
`

func (q *Queries) GetRefreshTokenByGraceHash(ctx context.Context, graceTokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByGraceHash, graceTokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.GraceTokenHash,
		&i.GraceExpiresAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, session_id, token_hash, expires_at, created_at, rotated_at, revoked_at, grace_token_hash, grace_expires_at FROM refresh_tokens WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.GraceTokenHash,
		&i.GraceExpiresAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND id != $2 AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessions, arg.UserID, arg.ID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionRefreshTokens = `-- name: RevokeSessionRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionRefreshTokens(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionRefreshTokens, sessionID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET token_hash = $2, expires_at = $3, rotated_at = now(),
    grace_token_hash = $4, grace_expires_at = $5
WHERE id = $1
RETURNING id, session_id, token_hash, expires_at, created_at, rotated_at, revoked_at, grace_token_hash, grace_expires_at
`

type RotateRefreshTokenParams struct {
	ID             pgtype.UUID        `json:"id"`
	TokenHash      []byte             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	GraceTokenHash []byte             `json:"grace_token_hash"`
	GraceExpiresAt pgtype.Timestamptz `json:"grace_expires_at"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.GraceTokenHash,
		arg.GraceExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.GraceTokenHash,
		&i.GraceExpiresAt,
	)
	return i, err
}
