// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, timezone, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, email_lower, display_name, timezone, password_hash, created_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	Timezone     string      `json:"timezone"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Timezone,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.DisplayName,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmailLower = `-- name: GetUserByEmailLower :one
SELECT id, email, email_lower, display_name, timezone, password_hash, created_at FROM users WHERE email_lower = lower($1)
`

func (q *Queries) GetUserByEmailLower(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailLower, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.DisplayName,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_lower, display_name, timezone, password_hash, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.DisplayName,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    timezone = COALESCE($3, timezone)
WHERE id = $1
RETURNING id, email, email_lower, display_name, timezone, password_hash, created_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Timezone    pgtype.Text `json:"timezone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.DisplayName,
		&i.Timezone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
