// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum TrackingConnectionState {
  idle,
  waiting,
  connecting,
  discovering,
  initializing,
  live,
  disconnected,
}

enum ExplorerDirection {
  read,
  write,
  notify,
  indicate,
  scan,
  connect,
  disconnect,
  marker,
}

class NativeCredentials {
  NativeCredentials({
    required this.baseUrl,
    required this.deviceId,
    required this.deviceToken,
    required this.hardwareId,
  });

  String baseUrl;

  String deviceId;

  String deviceToken;

  String hardwareId;

  List<Object?> _toList() {
    return <Object?>[
      baseUrl,
      deviceId,
      deviceToken,
      hardwareId,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCredentials decode(Object result) {
    result as List<Object?>;
    return NativeCredentials(
      baseUrl: result[0]! as String,
      deviceId: result[1]! as String,
      deviceToken: result[2]! as String,
      hardwareId: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class TrackingState {
  TrackingState({
    required this.enabled,
    required this.connectionState,
    this.batteryPercent,
    this.liquidPercent,
    this.isCharging,
    this.todayPuffCount,
    this.pendingUploads,
    this.lastError,
    this.simulationEnabled,
  });

  bool enabled;

  TrackingConnectionState connectionState;

  int? batteryPercent;

  int? liquidPercent;

  bool? isCharging;

  int? todayPuffCount;

  int? pendingUploads;

  String? lastError;

  bool? simulationEnabled;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      connectionState,
      batteryPercent,
      liquidPercent,
      isCharging,
      todayPuffCount,
      pendingUploads,
      lastError,
      simulationEnabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrackingState decode(Object result) {
    result as List<Object?>;
    return TrackingState(
      enabled: result[0]! as bool,
      connectionState: result[1]! as TrackingConnectionState,
      batteryPercent: result[2] as int?,
      liquidPercent: result[3] as int?,
      isCharging: result[4] as bool?,
      todayPuffCount: result[5] as int?,
      pendingUploads: result[6] as int?,
      lastError: result[7] as String?,
      simulationEnabled: result[8] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PuffInfo {
  PuffInfo({
    required this.startedAtEpochMs,
    required this.durationMs,
  });

  int startedAtEpochMs;

  int durationMs;

  List<Object?> _toList() {
    return <Object?>[
      startedAtEpochMs,
      durationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PuffInfo decode(Object result) {
    result as List<Object?>;
    return PuffInfo(
      startedAtEpochMs: result[0]! as int,
      durationMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PuffInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class StatusInfo {
  StatusInfo({
    this.batteryPercent,
    this.liquidPercent,
    this.isCharging,
    required this.recordedAtEpochMs,
  });

  int? batteryPercent;

  int? liquidPercent;

  bool? isCharging;

  int recordedAtEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      batteryPercent,
      liquidPercent,
      isCharging,
      recordedAtEpochMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static StatusInfo decode(Object result) {
    result as List<Object?>;
    return StatusInfo(
      batteryPercent: result[0] as int?,
      liquidPercent: result[1] as int?,
      isCharging: result[2] as bool?,
      recordedAtEpochMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StatusInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PairingResult {
  PairingResult({
    required this.success,
    this.address,
    this.errorMessage,
  });

  bool success;

  String? address;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      success,
      address,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static PairingResult decode(Object result) {
    result as List<Object?>;
    return PairingResult(
      success: result[0]! as bool,
      address: result[1] as String?,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PairingResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ExplorerScanFilter {
  ExplorerScanFilter({
    this.nameContains,
    this.minRssi,
  });

  String? nameContains;

  int? minRssi;

  List<Object?> _toList() {
    return <Object?>[
      nameContains,
      minRssi,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExplorerScanFilter decode(Object result) {
    result as List<Object?>;
    return ExplorerScanFilter(
      nameContains: result[0] as String?,
      minRssi: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExplorerScanFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ExplorerEvent {
  ExplorerEvent({
    required this.epochMs,
    required this.direction,
    this.serviceUuid,
    this.charUuid,
    required this.hex,
    this.note,
  });

  int epochMs;

  ExplorerDirection direction;

  String? serviceUuid;

  String? charUuid;

  String hex;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      epochMs,
      direction,
      serviceUuid,
      charUuid,
      hex,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExplorerEvent decode(Object result) {
    result as List<Object?>;
    return ExplorerEvent(
      epochMs: result[0]! as int,
      direction: result[1]! as ExplorerDirection,
      serviceUuid: result[2] as String?,
      charUuid: result[3] as String?,
      hex: result[4]! as String,
      note: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExplorerEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TrackingConnectionState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ExplorerDirection) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeCredentials) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TrackingState) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PuffInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is StatusInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PairingResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ExplorerScanFilter) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ExplorerEvent) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TrackingConnectionState.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ExplorerDirection.values[value];
      case 131: 
        return NativeCredentials.decode(readValue(buffer)!);
      case 132: 
        return TrackingState.decode(readValue(buffer)!);
      case 133: 
        return PuffInfo.decode(readValue(buffer)!);
      case 134: 
        return StatusInfo.decode(readValue(buffer)!);
      case 135: 
        return PairingResult.decode(readValue(buffer)!);
      case 136: 
        return ExplorerScanFilter.decode(readValue(buffer)!);
      case 137: 
        return ExplorerEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TrackingHostApi {
  /// Constructor for [TrackingHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TrackingHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setCredentials(NativeCredentials credentials) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.setCredentials$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[credentials]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> clearCredentials() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.clearCredentials$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String?> getActiveDeviceId() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.getActiveDeviceId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  Future<PairingResult> associateDevice() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.associateDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PairingResult?)!;
    }
  }

  Future<void> startTracking() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.startTracking$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopTracking() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.stopTracking$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<TrackingState> getTrackingState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.getTrackingState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as TrackingState?)!;
    }
  }

  Future<int> getPendingEventCount() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.getPendingEventCount$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<bool> isIgnoringBatteryOptimizations() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.isIgnoringBatteryOptimizations$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> requestIgnoreBatteryOptimizations() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.requestIgnoreBatteryOptimizations$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setSimulationEnabled(bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.setSimulationEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerStartScan(ExplorerScanFilter filter) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerStartScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filter]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerStopScan() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerStopScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerConnect(String address) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerConnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerDisconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerDisconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerWrite(String serviceUuid, String charUuid, String hex, bool withResponse) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerWrite$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuid, charUuid, hex, withResponse]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> explorerAddMarker(String note) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerAddMarker$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[note]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> explorerExportLog() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.vapen.TrackingHostApi.explorerExportLog$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }
}

abstract class TrackingFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onTrackingStateChanged(TrackingState state);

  void onPuff(PuffInfo puff);

  void onStatus(StatusInfo status);

  void onExplorerEvent(ExplorerEvent event);

  static void setUp(TrackingFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vapen.TrackingFlutterApi.onTrackingStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onTrackingStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TrackingState? arg_state = (args[0] as TrackingState?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onTrackingStateChanged was null, expected non-null TrackingState.');
          try {
            api.onTrackingStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vapen.TrackingFlutterApi.onPuff$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onPuff was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PuffInfo? arg_puff = (args[0] as PuffInfo?);
          assert(arg_puff != null,
              'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onPuff was null, expected non-null PuffInfo.');
          try {
            api.onPuff(arg_puff!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vapen.TrackingFlutterApi.onStatus$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onStatus was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final StatusInfo? arg_status = (args[0] as StatusInfo?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onStatus was null, expected non-null StatusInfo.');
          try {
            api.onStatus(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vapen.TrackingFlutterApi.onExplorerEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onExplorerEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ExplorerEvent? arg_event = (args[0] as ExplorerEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.vapen.TrackingFlutterApi.onExplorerEvent was null, expected non-null ExplorerEvent.');
          try {
            api.onExplorerEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
