// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.vapen.app.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VapenNativePigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class TrackingConnectionState(val raw: Int) {
  IDLE(0),
  WAITING(1),
  CONNECTING(2),
  DISCOVERING(3),
  INITIALIZING(4),
  LIVE(5),
  DISCONNECTED(6);

  companion object {
    fun ofRaw(raw: Int): TrackingConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ExplorerDirection(val raw: Int) {
  READ(0),
  WRITE(1),
  NOTIFY(2),
  INDICATE(3),
  SCAN(4),
  CONNECT(5),
  DISCONNECT(6),
  MARKER(7);

  companion object {
    fun ofRaw(raw: Int): ExplorerDirection? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCredentials (
  val baseUrl: String,
  val deviceId: String,
  val deviceToken: String,
  val hardwareId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCredentials {
      val baseUrl = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val deviceToken = pigeonVar_list[2] as String
      val hardwareId = pigeonVar_list[3] as String
      return NativeCredentials(baseUrl, deviceId, deviceToken, hardwareId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseUrl,
      deviceId,
      deviceToken,
      hardwareId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCredentials) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackingState (
  val enabled: Boolean,
  val connectionState: TrackingConnectionState,
  val batteryPercent: Long? = null,
  val liquidPercent: Long? = null,
  val isCharging: Boolean? = null,
  val todayPuffCount: Long? = null,
  val pendingUploads: Long? = null,
  val lastError: String? = null,
  val simulationEnabled: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingState {
      val enabled = pigeonVar_list[0] as Boolean
      val connectionState = pigeonVar_list[1] as TrackingConnectionState
      val batteryPercent = pigeonVar_list[2] as Long?
      val liquidPercent = pigeonVar_list[3] as Long?
      val isCharging = pigeonVar_list[4] as Boolean?
      val todayPuffCount = pigeonVar_list[5] as Long?
      val pendingUploads = pigeonVar_list[6] as Long?
      val lastError = pigeonVar_list[7] as String?
      val simulationEnabled = pigeonVar_list[8] as Boolean?
      return TrackingState(enabled, connectionState, batteryPercent, liquidPercent, isCharging, todayPuffCount, pendingUploads, lastError, simulationEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      connectionState,
      batteryPercent,
      liquidPercent,
      isCharging,
      todayPuffCount,
      pendingUploads,
      lastError,
      simulationEnabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TrackingState) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PuffInfo (
  val startedAtEpochMs: Long,
  val durationMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PuffInfo {
      val startedAtEpochMs = pigeonVar_list[0] as Long
      val durationMs = pigeonVar_list[1] as Long
      return PuffInfo(startedAtEpochMs, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startedAtEpochMs,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PuffInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StatusInfo (
  val batteryPercent: Long? = null,
  val liquidPercent: Long? = null,
  val isCharging: Boolean? = null,
  val recordedAtEpochMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusInfo {
      val batteryPercent = pigeonVar_list[0] as Long?
      val liquidPercent = pigeonVar_list[1] as Long?
      val isCharging = pigeonVar_list[2] as Boolean?
      val recordedAtEpochMs = pigeonVar_list[3] as Long
      return StatusInfo(batteryPercent, liquidPercent, isCharging, recordedAtEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      batteryPercent,
      liquidPercent,
      isCharging,
      recordedAtEpochMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StatusInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PairingResult (
  val success: Boolean,
  val address: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PairingResult {
      val success = pigeonVar_list[0] as Boolean
      val address = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      return PairingResult(success, address, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      address,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PairingResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplorerScanFilter (
  val nameContains: String? = null,
  val minRssi: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplorerScanFilter {
      val nameContains = pigeonVar_list[0] as String?
      val minRssi = pigeonVar_list[1] as Long?
      return ExplorerScanFilter(nameContains, minRssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nameContains,
      minRssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ExplorerScanFilter) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplorerEvent (
  val epochMs: Long,
  val direction: ExplorerDirection,
  val serviceUuid: String? = null,
  val charUuid: String? = null,
  val hex: String,
  val note: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplorerEvent {
      val epochMs = pigeonVar_list[0] as Long
      val direction = pigeonVar_list[1] as ExplorerDirection
      val serviceUuid = pigeonVar_list[2] as String?
      val charUuid = pigeonVar_list[3] as String?
      val hex = pigeonVar_list[4] as String
      val note = pigeonVar_list[5] as String?
      return ExplorerEvent(epochMs, direction, serviceUuid, charUuid, hex, note)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      epochMs,
      direction,
      serviceUuid,
      charUuid,
      hex,
      note,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ExplorerEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return VapenNativePigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class VapenNativePigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TrackingConnectionState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExplorerDirection.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCredentials.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingState.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PuffInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PairingResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplorerScanFilter.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplorerEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TrackingConnectionState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ExplorerDirection -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is NativeCredentials -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is TrackingState -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PuffInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is StatusInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PairingResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ExplorerScanFilter -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ExplorerEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TrackingHostApi {
  fun setCredentials(credentials: NativeCredentials)
  fun clearCredentials()
  fun getActiveDeviceId(): String?
  fun associateDevice(callback: (Result<PairingResult>) -> Unit)
  fun startTracking()
  fun stopTracking()
  fun getTrackingState(): TrackingState
  fun getPendingEventCount(): Long
  fun isIgnoringBatteryOptimizations(): Boolean
  fun requestIgnoreBatteryOptimizations()
  fun setSimulationEnabled(enabled: Boolean)
  fun explorerStartScan(filter: ExplorerScanFilter)
  fun explorerStopScan()
  fun explorerConnect(address: String)
  fun explorerDisconnect()
  fun explorerWrite(serviceUuid: String, charUuid: String, hex: String, withResponse: Boolean)
  fun explorerAddMarker(note: String)
  fun explorerExportLog(): String

  companion object {
    /** The codec used by TrackingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VapenNativePigeonPigeonCodec()
    }
    /** Sets up an instance of `TrackingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TrackingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.setCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as NativeCredentials
            val wrapped: List<Any?> = try {
              api.setCredentials(credentialsArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.clearCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearCredentials()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.getActiveDeviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getActiveDeviceId())
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.associateDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.associateDevice{ result: Result<PairingResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VapenNativePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VapenNativePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.startTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startTracking()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.stopTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopTracking()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.getTrackingState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getTrackingState())
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.getPendingEventCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPendingEventCount())
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.isIgnoringBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isIgnoringBatteryOptimizations())
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.requestIgnoreBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestIgnoreBatteryOptimizations()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.setSimulationEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setSimulationEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerStartScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as ExplorerScanFilter
            val wrapped: List<Any?> = try {
              api.explorerStartScan(filterArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerStopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.explorerStopScan()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerConnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.explorerConnect(addressArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerDisconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.explorerDisconnect()
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerWrite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidArg = args[0] as String
            val charUuidArg = args[1] as String
            val hexArg = args[2] as String
            val withResponseArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.explorerWrite(serviceUuidArg, charUuidArg, hexArg, withResponseArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerAddMarker$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val noteArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.explorerAddMarker(noteArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vapen.TrackingHostApi.explorerExportLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.explorerExportLog())
            } catch (exception: Throwable) {
              VapenNativePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TrackingFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TrackingFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      VapenNativePigeonPigeonCodec()
    }
  }
  fun onTrackingStateChanged(stateArg: TrackingState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vapen.TrackingFlutterApi.onTrackingStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapenNativePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPuff(puffArg: PuffInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vapen.TrackingFlutterApi.onPuff$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(puffArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapenNativePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStatus(statusArg: StatusInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vapen.TrackingFlutterApi.onStatus$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapenNativePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onExplorerEvent(eventArg: ExplorerEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vapen.TrackingFlutterApi.onExplorerEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapenNativePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
